//! # D-Bus interface proxy for: `org.freedesktop.ScreenSaver`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/org/freedesktop/ScreenSaver' from service 'org.freedesktop.ScreenSaver' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "org.freedesktop.ScreenSaver",
    default_service = "org.freedesktop.ScreenSaver",
    default_path = "/org/freedesktop/ScreenSaver"
)]
pub trait ScreenSaver {
    /// GetActive method
    fn get_active(&self) -> zbus::Result<bool>;

    /// GetActiveTime method
    fn get_active_time(&self) -> zbus::Result<u32>;

    /// GetSessionIdleTime method
    fn get_session_idle_time(&self) -> zbus::Result<u32>;

    /// Inhibit method
    fn inhibit(&self, application_name: &str, reason_for_inhibit: &str) -> zbus::Result<u32>;

    /// Lock method
    fn lock(&self) -> zbus::Result<()>;

    /// SetActive method
    fn set_active(&self, e: bool) -> zbus::Result<bool>;

    /// SimulateUserActivity method
    fn simulate_user_activity(&self) -> zbus::Result<()>;

    /// Throttle method
    fn throttle(&self, application_name: &str, reason_for_inhibit: &str) -> zbus::Result<u32>;

    /// UnInhibit method
    fn un_inhibit(&self, cookie: u32) -> zbus::Result<()>;

    /// UnThrottle method
    fn un_throttle(&self, cookie: u32) -> zbus::Result<()>;

    /// ActiveChanged signal
    #[zbus(signal)]
    fn active_changed(&self, arg_1: bool) -> zbus::Result<()>;
}
