//! # D-Bus interface proxy for: `org.kde.KWin.VirtualDesktopManager`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/VirtualDesktopManager' from service 'org.kde.KWin' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,

use zbus::proxy;

#[proxy(
    interface = "org.kde.KWin.VirtualDesktopManager",
    default_service = "org.kde.KWin",
    default_path = "/VirtualDesktopManager"
)]
pub trait VirtualDesktopManager {
    /// createDesktop method
    #[zbus(name = "createDesktop")]
    fn create_desktop(&self, position: u32, name: &str) -> zbus::Result<()>;

    /// removeDesktop method
    #[zbus(name = "removeDesktop")]
    fn remove_desktop(&self, id: &str) -> zbus::Result<()>;

    /// setDesktopName method
    #[zbus(name = "setDesktopName")]
    fn set_desktop_name(&self, id: &str, name: &str) -> zbus::Result<()>;

    /// countChanged signal
    #[zbus(signal, name = "countChanged")]
    fn count_changed_method(&self, count: u32) -> zbus::Result<()>;

    /// currentChanged signal
    #[zbus(signal, name = "currentChanged")]
    fn current_changed_method(&self, id: &str) -> zbus::Result<()>;

    /// desktopCreated signal
    #[zbus(signal, name = "desktopCreated")]
    fn desktop_created(&self, id: &str, desktop_data: (u32, &str, &str)) -> zbus::Result<()>;

    /// desktopDataChanged signal
    #[zbus(signal, name = "desktopDataChanged")]
    fn desktop_data_changed(&self, id: &str, desktop_data: (u32, &str, &str)) -> zbus::Result<()>;
    /// desktopRemoved signal
    #[zbus(signal, name = "desktopRemoved")]
    fn desktop_removed(&self, id: &str) -> zbus::Result<()>;

    /// navigationWrappingAroundChanged signal
    #[zbus(signal, name = "navigationWrappingAroundChanged")]
    fn navigation_wrapping_around_changed_method(
        &self,
        navigation_wrapping_around: bool,
    ) -> zbus::Result<()>;

    /// rowsChanged signal
    #[zbus(signal, name = "rowsChanged")]
    fn rows_changed_method(&self, rows: u32) -> zbus::Result<()>;

    /// count property
    #[zbus(property, name = "count")]
    fn count(&self) -> zbus::Result<u32>;

    /// current property (returns the ID of the current virtual desktop)
    #[zbus(property, name = "current")]
    fn current(&self) -> zbus::Result<String>;

    /// Set current desktop (ID)
    #[zbus(property, name = "current")]
    fn set_current(&self, value: &str) -> zbus::Result<()>;

    /// desktops property
    #[zbus(property, name = "desktops")]
    fn desktops(&self) -> zbus::Result<Vec<(u32, String, String)>>;

    /// navigationWrappingAround property
    #[zbus(property, name = "navigationWrappingAround")]
    fn navigation_wrapping_around(&self) -> zbus::Result<bool>;

    #[zbus(property, name = "navigationWrappingAround")]
    fn set_navigation_wrapping_around_method(&self, value: bool) -> zbus::Result<()>;

    /// rows property
    #[zbus(property, name = "rows")]
    fn rows(&self) -> zbus::Result<u32>;
    #[zbus(property, name = "rows")]
    fn set_rows(&self, value: u32) -> zbus::Result<()>;
}
