[package]
edition = "2024"
name = "timings-app"
description = ""
publish = false
version = "0.0.1"

[dependencies]
trayicon = { git = "https://github.com/Ciantic/trayicon-rs", branch = "master" }
smithay-client-toolkit = "0.20.0"
egui = "0.34.2"
wayapp = { git = "https://github.com/Ciantic/wayapp", branch = "suspend_optimization" }
tokio = { version = "1.52.3", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
clap = { version = "4.6", features = ["derive"] }

single-instance = { path = "../single-instance" }
virtual-desktops = { path = "../virtual-desktops" }
idle-monitor = { path = "../idle-monitor" }
timings = { path = "../timings" }

sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite"] }
futures = "0.3.32"
chrono = { version = "0.4", features = ["serde"] }
log = "0.4.29"
env_logger = "0.11"

# Debugging and profiling
hotpath = "0.16"

[features]
hotpath = ["hotpath/hotpath", "hotpath/hotpath-alloc"]
